# Generated by Django 4.2.4 on 2023-09-24 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('cover_photo', models.ImageField(upload_to='project/cover/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=600)),
                ('status', models.BooleanField(default=True)),
                ('composite_pk', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='project_categories', to='accounts.category')),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('mods', models.ManyToManyField(blank=True, related_name='projects_mods', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.ManyToManyField(blank=True, related_name='projects_solicitation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField()),
                ('text', models.TextField(blank=True, max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('composite_pk', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField()),
                ('text', models.TextField(blank=True, max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('composite_pk', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.post')),
            ],
        ),
    ]
