# Generated by Django 4.2.4 on 2023-08-29 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField()),
                ('text', models.TextField(blank=True, max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('composite_pk', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField()),
                ('text', models.TextField(blank=True, max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('composite_pk', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.post')),
            ],
        ),
    ]
