# Generated by Django 4.2.4 on 2023-09-14 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_project_members_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mods',
            field=models.ManyToManyField(blank=True, related_name='projects_mods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='solicitation',
            field=models.ManyToManyField(blank=True, related_name='projects_solicitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
