# Generated by Django 4.2.4 on 2023-09-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_birth_date_alter_customuser_city_and_more'),
        ('projects', '0005_project_mods_project_solicitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='project_categories', to='accounts.category'),
        ),
    ]
