# Generated by Django 4.2.4 on 2023-09-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_categories'),
        ('projects', '0006_project_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='project_categories', to='accounts.category'),
        ),
    ]
