# Generated by Django 4.2.4 on 2023-08-23 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('review_body', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user', to=settings.AUTH_USER_MODEL)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviwed_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
