# Generated by Django 4.2.4 on 2023-09-16 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_mods_project_solicitation'),
        ('accounts', '0004_alter_customuser_birth_date_alter_customuser_city_and_more'),
    ]
    
    operations = [
        migrations.DeleteModel(name='review'),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('composite_pk', models.CharField(default='default', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('review_id', models.IntegerField()),
                ('review_body', models.TextField(max_length=200)),
                ('review_value', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user', to=settings.AUTH_USER_MODEL)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviwed_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project'))
            ],
        ),
    ]
